apiVersion: v1
kind: Service
metadata:
  name: micro-gateway
  labels:
    app: micro
spec:
  ports:
    - port: 3000
  selector:
    app: micro 
    tier: gateway
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: micro-gateway
  labels:
    app: micro
spec:
  selector:
    matchLabels:
      app: micro
      tier: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: micro
        tier: gateway
    spec:
      containers:
      - image: 192.168.31.51:5000/micro/gateway:v1.0.0
        name: micro-gateway
        env:
        - name: ZOOKEEPER_HOST
          value: zk-headless
        ports:      
        - containerPort: 3000
          name: wordpress