apiVersion: v1
kind: Service
metadata:
  name: micro-service
  labels:
    app: micro 
spec:
  ports:
    - port: 4000
  selector:
    app: micro 
    tier: service 
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: micro-service
  labels:
    app: micro
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: micro
      tier: service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: micro
        tier: service
    spec:
      containers:
      - image: 192.168.31.51:5000/micro/service:v1.0.0
        name: micro-service
        env:
        - name: ZOOKEEPER_HOST
          value: zk-headless
        ports:      
        - containerPort: 4000
          name: wordpress