kind: Service
apiVersion: v1
metadata:
  name: node-in-docker-service
spec:
  selector:
    app: node-in-docker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
